{
 "title": "Project 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Process Uptime",
   "type": "stat",
   "description": "Make sure of any dips and downtimes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" },
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Project1 Error Rate",
   "type": "stat",
   "description": "How many errors have been caused in the last 5mins",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(logback_events_total{job=\"project1rev\", level=\"error\"}[5m])"
    },
    {
     "expr": "http_server_requests_seconds_sum{exception=\"None\", job=\"project1rev\", method=\"GET\", outcome=\"CLIENT_ERROR\", status=\"404\", uri=\"/**\"}"
    }
   ]
  },
  {
   "title": "HTTP request latency rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{exception=\"None\", job=\"project1rev\", method=\"GET\", outcome=\"SUCCESS\", status=\"200\", uri=\"/actuator/prometheus\"}"
    },
    {
     "expr": "http_server_requests_seconds_max{exception=\"None\", job=\"project1rev\", method=\"GET\", outcome=\"SUCCESS\", status=\"200\", uri=\"/user/login/{email}/{password}\"}"
    }
   ]
  },
  {
   "title": "Important methods Latency Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "adding_to_cart_time_seconds_max {exception=\"None\"}"
    },
    {
     "expr": "show_cart_time_seconds_max {exception=\"None\"}"
    },
    {
     "expr": "show_register_time_seconds_max {exception=\"None\"}"
    },
    {
     "expr": "show_users_time_seconds_max {exception=\"None\"}"
    }
   ]
  },
  {
   "title": "JVM memory usage stats",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{id=\"direct\", job=\"project1rev\"}"
    },
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\", job=\"project1rev\"}"
    },
    { "expr": "jvm_threads_live_threads" },
    {
     "expr": "rate(jvm_memory_used_bytes{area=\"heap\", id=\"PS Eden Space\", job=\"project1rev\"}[5m])"
    }
   ]
  }
 ]
}