apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2
  labels:
    app: project2
spec:
  selector:
    matchLabels:
      app: project2
  replicas: 1
  template:
    metadata:
      labels:
        app: project2
    spec:
      containers:
        - name: project2rev
          image: dogistan/project2rev:3rdrelease
          ports:
          - containerPort: 8085
            name: http
            protocol: TCP 
---

apiVersion: v1
kind: Service
metadata:
  name: project2-service
spec:
  selector:
    app: project2
  ports:
    - name: http
      protocol : TCP 
      port: 8085
      targetPort: 8085
      nodePort: 30010
  type: LoadBalancer
  
